api_version = "2026-04"

name = "Thank You - FAQ Section"
type = "ui_extension"
uid = "b3e90b28-925f-7636-1b94-23707aefafd81160f1a9"

[[targeting]]
module = "./src/index.jsx"
target = "purchase.thank-you.block.render"

[capabilities]
api_access = true
network_access = true
multiple = false

[[metafields]]
namespace = "$app"
key = "requestedFreeGift"
