api_version = "2026-04"

name = "Thank You - FAQ Section"
type = "ui_extension"
uid = "b3e90b28-925f-7636-1b94-23707aefafd81160f1a9"

[[targeting]]
module = "./src/index.jsx"
target = "purchase.thank-you.block.render"

[capabilities]
api_access = true
network_access = true

[[metafields]]
namespace = "$app"
key = "requestedFreeGift"

[settings]

[[settings.fields]]
key = "faq_q1"
type = "single_line_text_field"
name = "FAQ Question 1"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a1"
type = "multi_line_text_field"
name = "FAQ Answer 1"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q2"
type = "single_line_text_field"
name = "FAQ Question 2"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a2"
type = "multi_line_text_field"
name = "FAQ Answer 2"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q3"
type = "single_line_text_field"
name = "FAQ Question 3"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a3"
type = "multi_line_text_field"
name = "FAQ Answer 3"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q4"
type = "single_line_text_field"
name = "FAQ Question 4"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a4"
type = "multi_line_text_field"
name = "FAQ Answer 4"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q5"
type = "single_line_text_field"
name = "FAQ Question 5"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a5"
type = "multi_line_text_field"
name = "FAQ Answer 5"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q6"
type = "single_line_text_field"
name = "FAQ Question 6"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a6"
type = "multi_line_text_field"
name = "FAQ Answer 6"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q7"
type = "single_line_text_field"
name = "FAQ Question 7"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a7"
type = "multi_line_text_field"
name = "FAQ Answer 7"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q8"
type = "single_line_text_field"
name = "FAQ Question 8"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a8"
type = "multi_line_text_field"
name = "FAQ Answer 8"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q9"
type = "single_line_text_field"
name = "FAQ Question 9"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a9"
type = "multi_line_text_field"
name = "FAQ Answer 9"
[[settings.fields.validations]]
name = "max"
value = "240"

[[settings.fields]]
key = "faq_q10"
type = "single_line_text_field"
name = "FAQ Question 10"
[[settings.fields.validations]]
name = "max"
value = "80"

[[settings.fields]]
key = "faq_a10"
type = "multi_line_text_field"
name = "FAQ Answer 10"
[[settings.fields.validations]]
name = "max"
value = "240"
