api_version = "2026-01"

name = "Thank You - Discount Section"
type = "ui_extension"
uid = "b8d84524-0368-11a3-eae7-d5d23b0429c29e362e72"

[[targeting]]
module = "./src/index.jsx"
target = "purchase.thank-you.block.render"

[[targeting]]
module = "./src/index.jsx"
target = "purchase.checkout.block.render"

[capabilities]
api_access = true
network_access = true


