api_version = "2026-01"

[[extensions]]
name = "Thank You - Loyalty Section"
handle = "thank-you-loyalty"
type = "ui_extension"
uid = "f6b4c1ca-3584-2747-cca3-a78ca96a744b17d53dc3"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
api_access = true
network_access = true

[[extensions.metafields]]
namespace = "$app"
key = "requestedFreeGift"
